In [69]:
import numpy as np

In [70]:
v1 = np.array([1, 1, 0, 0], dtype=float)
v1 /= np.linalg.norm(v1)
P1 = np.outer(v1, v1) / np.dot(v1, v1)
v1

array([0.70710678, 0.70710678, 0.        , 0.        ])

In [71]:
v2 = np.array([0, 0, 1, -1], dtype=float)
v2 /= np.linalg.norm(v2)
P2 = np.outer(v2, v2) / np.dot(v2, v2)
v2

array([ 0.        ,  0.        ,  0.70710678, -0.70710678])

In [72]:
P = P1 + P2

u, s, vt = np.linalg.svd(P)

u[:, :2].T @ v1

array([-1.,  0.])

In [73]:
u[:, :2].T @ v2

array([ 0., -1.])

In [74]:
u[:, 2:].T @ v1

array([0., 0.])

In [75]:
u[:, 2:].T @ v2

array([0., 0.])